### ISSUE TITLE
Unknown encoding 'base64url'

### ISSUE THREAD

**Issue by matteoolefloch** [postalsys/emailengine#107]
**Describe the bug**
Got this error when I try to access in the dashboard to the account of a user, got the same error about base64url, on the callback url oauth2. I tried 3 main node version 12.22.8/14.17.5/16.13.1, I also got the base64url error on my backend when trying to generate the hosted-ui link with your code sample, I used the [base64url](https://www.npmjs.com/package/base64url) package to fix it, for convert the base64 to base64url. I got this error only when getting the last master version, when I run emailengine in docker (docker hub image) the account section is accessible 

```
[1640080365641] ERROR (11996 on MacBook-Pro-de-Matteo.local): Unknown encoding: base64url
    tid: 7
    path: "/admin/accounts/d3b54c6c-6748-4498-8a62-d01d6873c3d9"
    method: "get"
    err: {
      "type": "NodeError",
      "message": "Unknown encoding: base64url",
      "stack":
          TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url
              at Buffer.toString (buffer.js:802:11)
              at getSignedFormData (/Users/matteolefloch/Developer/breakCold/emailengine/lib/routes-ui.js:263:25)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at async handler (/Users/matteolefloch/Developer/breakCold/emailengine/lib/routes-ui.js:2522:34)
              at async exports.Manager.execute (/Users/matteolefloch/Developer/breakCold/emailengine/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
              at async Object.internals.handler (/Users/matteolefloch/Developer/breakCold/emailengine/node_modules/@hapi/hapi/lib/handler.js:46:20)
              at async exports.execute (/Users/matteolefloch/Developer/breakCold/emailengine/node_modules/@hapi/hapi/lib/handler.js:31:20)
              at async Request._lifecycle (/Users/matteolefloch/Developer/breakCold/emailengine/node_modules/@hapi/hapi/lib/request.js:371:32)
              at async Request._execute (/Users/matteolefloch/Developer/breakCold/emailengine/node_modules/@hapi/hapi/lib/request.js:281:9)
      "code": "ERR_UNKNOWN_ENCODING",
      "isBoom": true,
      "isServer": true,
      "data": null,
      "output": {
        "statusCode": 500,
        "payload": {
          "statusCode": 500,
          "error": "Internal Server Error",
          "message": "An internal server error occurred"
        },
        "headers": {}
      },
      "isDeveloperError": true
    }

```

**Desktop (please complete the following information):**
 - OS: windows and macOS 
 - Browser [e.g. chrome, safari] every browser

**Comment by andris9** [comment]
Can you check what is the exact Node.js version you are using?

**Comment by matteoolefloch** [comment]
Hey, I try in 3 nodes version 12.22.8/14.17.5/16.13.1

**Comment by andris9** [comment]
I can't confirm. 'base64url' is a valid encoding type both in Node 14 and 16. When I try to run the version in master, everything is just fine. Are you sure you are running the correct version of Node.js? Open the EmailEngine dashboard and double check if it displays 16.13.1 or something else:

<img width="846" alt="Screenshot 2021-12-21 at 15 18 04" src="https://user-images.githubusercontent.com/132242/146936476-00a43123-4337-4239-834d-9e135e4b8d27.png">

**Comment by matteoolefloch** [comment]
On node 14 its was not working for me, I retry in node 16.13.1 (fresh install) and its works thanks for you help ! 😅

**Comment by andris9** [comment]
Great 👍
