### ISSUE TITLE
OpenAPI client generation fails

### ISSUE THREAD

**Issue by brennerm** [postalsys/emailengine#340]
**Describe the bug**
The generation of an API client using the openapi-generator-cli fails with the following error:
```
Exception in thread "main" java.lang.IllegalArgumentException: Cannot deserialize value of type `java.util.Date` from String "false": not a valid representation (error: Failed to parse Date value 'false': Cannot parse date "false": not compatible with any of standard forms ("yyyy-MM-dd'T'HH:mm:ss.SSSX", "yyyy-MM-dd'T'HH:mm:ss.SSS", "EEE, dd MMM yyyy HH:mm:ss zzz", "yyyy-MM-dd"))
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.swagger.v3.oas.models.media.DateSchema["enum"]->java.util.ArrayList[0])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4449)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4380)
        at io.swagger.v3.core.util.ModelDeserializer.deserialize(ModelDeserializer.java:73)
        at io.swagger.v3.core.util.ModelDeserializer.deserialize(ModelDeserializer.java:33)
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4444)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4380)
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:1212)
        at io.swagger.v3.parser.converter.SwaggerConverter.convert(SwaggerConverter.java:262)
        at io.swagger.v3.parser.converter.SwaggerConverter.readResult(SwaggerConverter.java:104)
        at io.swagger.v3.parser.converter.SwaggerConverter.readLocation(SwaggerConverter.java:85)
        at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:589)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:647)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:479)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

This is due to the nextAttempt field using the format _date_ but also providing an enum that contains the value _false_, which is no valid date obviously. Removing the enum leads to the generation working.
```
...
    "nextAttempt": {
      "type": "string",
      "format": "date",
      "description": "Next delivery attempt",
      "example": "2021-02-17T13:43:18.860Z",
      "enum": [
        false
      ]
    },
...
```

**To Reproduce**
1. Execute `openapi-generator-cli generate -g typescript-nestjs -i https://api.emailengine.app/swagger.json -o email-engine-nestjs` 
2. See error

**Expected behavior**
The API client is being generated without any error.

**Comment by brennerm** [comment]
@andris9 Thanks for fixing this issue. Unfortunately there are two additional places that lead to the generation of a non-working API client. It's the enum value in these two fields:
```
...
    "clientSecret": {
      "type": "string",
      "description": "Client secret for 3-legged OAuth2 applications. Actual value is not revealed.",
      "enum": [
        "******"
      ]
    },
    "serviceKey": {
      "type": "string",
      "description": "PEM formatted service secret for 2-legged OAuth2 applications. Actual value is not revealed.",
      "enum": [
        "******"
      ]
    },
...
```
When using the _typescript-node_ generator I end up with the following build errors:
```
$ npm run build

> email-engine-api-client@2.32.13 build
> tsc && tsc -p tsconfig.esm.json

api.ts:1148:5 - error TS1136: Property assignment expected.

1148     : '******',
         ~

api.ts:1149:26 - error TS1005: ';' expected.

1149     UnknownDefaultOpenApi: '11184809'
                              ~

api.ts:1150:1 - error TS1128: Declaration or statement expected.

1150 } as const;
     ~

api.ts:1150:3 - error TS1434: Unexpected keyword or identifier.

1150 } as const;
       ~~

api.ts:5805:5 - error TS1136: Property assignment expected.

5805     : '******',
         ~

api.ts:5806:26 - error TS1005: ';' expected.

5806     UnknownDefaultOpenApi: '11184809'
                              ~

api.ts:5807:1 - error TS1128: Declaration or statement expected.

5807 } as const;
     ~

api.ts:5807:3 - error TS1434: Unexpected keyword or identifier.

5807 } as const;
       ~~


Found 8 errors in the same file, starting at: api.ts:1148

```

Can you take a look at this or should I create a new ticket for this?

**Comment by andris9** [comment]
The root issue is that the [swagger file](https://api.emailengine.app/swagger.json) is generated automatically from [Joi schemas](https://joi.dev/api/), which defines the API structure, and Joi is not 100% compatible with OpenAPI. For example, EmailEngine uses conditionals quite a lot, and these are not reflected in the swagger.json at all. Instead, you can read about these conditions from the descriptions of specific fields (e.g. if field X has value Y, then field Z is required, otherwise optional).

I fixed the specific enums with this commit https://github.com/postalsys/emailengine/commit/87e373d2d3b6767b1acdd7856b130e767d74a97d but this only opened another set of issues, and I'm afraid it would continue for a quite a while to get everything fixed - seems too much effort on my side 🙄

**Comment by brennerm** [comment]
@andris9 Thanks for your work. Not sure which issues you are experiencing but generating a working API client works now on my end using the following command:
`openapi-generator-cli generate -g typescript-axios -i https://api.emailengine.app/swagger.json`
Huge thanks! :pray:
