### ISSUE TITLE
Retrieving the full logs is sometimes not possible. Can we limit the lrange?

### ISSUE THREAD

**Issue by matthiaz** [postalsys/emailengine#452]
**Please file only reproducible bugs.**

I have an instance of emailengine running with upstash as redis backend

When I try to retrieve logs, it gives me the following error.

```
Failed to process logs
ReplyError: ERR max request size exceeded. Limit: 1048576 bytes, Actual: 1277695 bytes. See https://upstash.com/docs/redis/troubleshooting/max_request_size_exceeded for details
    at getLogs (/emailengine/lib/tools.js:1014:14)
    at handler (/emailengine/lib/routes-ui.js:7556:20)
    at exports.Manager.execute (/emailengine/node_modules/@hapi/hapi/lib/toolkit.js:57:29)
    at internals.handler (/emailengine/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/emailengine/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (/emailengine/node_modules/@hapi/hapi/lib/request.js:370:68)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._execute (/emailengine/node_modules/@hapi/hapi/lib/request.js:280:9)
```

This is because line 1014 https://github.com/postalsys/emailengine/blob/master/lib/tools.js#L1014
is requesting `LRANGE <LOGKEY> 0 -1`, which means 'everything' in redis. 
But upstash is limited to a 1MB request size.

Would it be possible to lower the request size? Or make this configurable?

I believe something like this: `.lrangeBuffer(logKey, -100, -1)` would only get the last 100 logs.

**Comment by andris9** [comment]
The logs feature is a convenience option. It is probably not a good idea to store too much log information in Redis.

If you need more logs, then use the output log from EmailEngine, as it contains much more information. EmailEngine writes logs to stdout, so it depends on your deployment setup where the actual log files are. If you use Docker, then see container log files. If you use Systemd, then check journald or syslog. See https://emailengine.app/logging for more information.

**Comment by andris9** [comment]
Btw, if your Redis setup limits command size, then you can't use email sending with attachments as well because EmailEngine writes all queued emails as large blobs to Redis. These values can easily be bigger than 1MB.

**Comment by matthiaz** [comment]
That's very good to know, thank you.
