### ISSUE TITLE
preProcessHtml for Outlook is throwing 500 errors

### ISSUE THREAD

**Issue by Jivings** [postalsys/emailengine#482]
**Describe the bug**
Enabling `preProcessHtml` option when fetching messages is throwing a 500 error

**To Reproduce**
Make a request like this for an Outlook account:

```
await axios({
  url: `/v1/account/${accountId}/message/${messageId}`,
  method: 'GET',
  params: {
    textType: '*',
    preProcessHtml: true,
   }
});
```

It throws a 500 error, which logs like this on the server:

```
{
  "level": 50,
  "time": 1733217555173,
  "pid": 7,
  "hostname": "15b3425cb189",
  "tid": 2,
  "msg": "Command failed",
  "cmd": "call",
  "mid": "1733217554969:14082",
  "message": {
    "cmd": "getMessage",
    "account": "f5b723d9-8386-43bb-aae1-edbbfbcaa5c4",
    "message": "AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0A54bleiMoak6MninFORBrzgAAGNPrmgAA",
    "options": {
      "textType": "*",
      "webSafeHtml": true,
      "embedAttachedImages": true,
      "preProcessHtml": true,
      "markAsSeen": false,
      "documentStore": false
    },
    "timeout": 0
  },
  "err": {
    "type": "ReferenceError",
    "message": "document is not defined",
    "stack": "ReferenceError: document is not defined\n    at /emailengine/node_modules/nwsapi/src/nwsapi.js:215:21\n    at Factory (/emailengine/node_modules/nwsapi/src/nwsapi.js:245:6)\n    at initNwsapi (/emailengine/node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:10:10)\n    at exports.addNwsapi (/emailengine/node_modules/jsdom/lib/jsdom/living/helpers/selectors.js:38:24)\n    at HTMLBodyElementImpl.querySelectorAll (/emailengine/node_modules/jsdom/lib/jsdom/living/nodes/ParentNode-impl.js:77:21)\n    at HTMLBodyElement.querySelectorAll (/emailengine/node_modules/jsdom/lib/jsdom/living/generated/Element.js:1119:58)\n    at mimeHtml (/emailengine/node_modules/@postalsys/email-text-tools/lib/mime-html.js:138:25)\n    at OutlookClient.getMessage (/emailengine/lib/email-client/outlook-client.js:1201:42)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async ConnectionHandler.getMessage (/emailengine/workers/imap.js:396:16)"
  }
}
```

**Comment by andris9** [comment]
Github is not  good channel for time critical issues as I rarely check it (EmailEngine is not open source software and not developed by a community). Instead use the support email address.

Could you try upgrading to v2.49.2 and see if this fixes your issue with the `preProcessHtml` option?

**Comment by Jivings** [comment]
I haven't raised anything time-critical, just bugs.

The other issue I was just dumping my thoughts as I was debugging it, sorry if that was annoying.
